name: LeetCode Stats Report

on:
  workflow_dispatch:
    inputs:
      days:
        description: 'Number of days to look back (default 7)'
        required: false
        default: '7'

  schedule:
    - cron: '0 5 * * *'  # 6 AM London time daily

jobs:
  run-stats:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run CLI and save output
        id: run-script
        run: |
          DAYS="${{ github.event.inputs.days || '1' }}"

          echo "Running stats for over $DAYS days"
          OUTPUT=$(python -m leetcode_accountability.cli stats --days $DAYS)
          echo "${OUTPUT}"
          # Save output in a way GitHub can pass it to the next step
          echo "output<<EOF" >> $GITHUB_OUTPUT
          echo "$OUTPUT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Send email with output as body
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "📊 Daily Coding Group: Leetcode Stats Report"
          to: nyakundi@hotmail.co.uk
          from: LeetCode Accoutability Bot <${{ secrets.EMAIL_USERNAME }}>
          body: |
            Hello,

            Here is your Daily LeetCode stats report:

            ${{ steps.run-script.outputs.output }}

            – GitHub Actions Bot
