name: LeetCode Stats Report

on:
  workflow_dispatch:
    inputs:
      days:
        description: 'Number of days to look back.'
        required: false
        default: '1'
      start_date:
        description: 'Start Dat. format: YYYY-MM-DDTHH:MM:SS or None/null'
        required: false
        default: 'None'
      end_date:
        description: 'End Date. format: YYYY-MM-DDTHH:MM:SS or None/null'
        required: false
        default: 'None'
      output_type:
        description: 'Either text or html.'
        required: false
        default: 'html'
      email_to:
        description: 'Email address to send the report to.'
        required: false
        default: 'daily-coding-group@googlegroups.com'

  schedule:
    - cron: '30 2 * * *'  # 6 AM London time daily

jobs:
  run-stats:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run CLI
        id: run-script
        run: |
          DAYS="${{ github.event.inputs.days || '1' }}"
          START_DATE="${{ github.event.inputs.start_date }}"
          END_DATE="${{ github.event.inputs.end_date }}"
          OUTPUT_TYPE="${{ github.event.inputs.output_type || 'html' }}"

          python -m leetcode_accountability.cli stats --days $DAYS --start-date $START_DATE --end-date $END_DATE --output-type $OUTPUT_TYPE

      - name: Send email with output as body
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "📊 Daily Coding Group: Leetcode Stats Report"
          to: ${{ github.event.inputs.email_to || 'daily-coding-group@googlegroups.com' }}
          from: LeetCode Accoutability Bot <${{ secrets.EMAIL_USERNAME }}>
          html_body: file://report.html
