name: LeetCode Stats Report

on:
  workflow_dispatch:
    inputs:
      days:
        description: 'Number of days to look back.'
        required: false
        default: '1'
      output_type:
        description: 'Either text or html.'
        required: false
        default: 'html'
      report_file:
        description: 'Path of the report file.'
        required: false
        default: 'report.html'

  schedule:
    - cron: '0 5 * * *'  # 6 AM London time daily

jobs:
  run-stats:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run CLI and save output
        id: run-script
        run: |
          DAYS="${{ github.event.inputs.days || '1' }}"
          OUTPUT_TYPE="${{ github.event.inputs.output_type || 'text' }}"
          REPORT_FILE="${{ github.event.inputs.report_file || 'report.html' }}"

          echo "Running stats for over $DAYS days"
          OUTPUT=$(python -m leetcode_accountability.cli stats --days $DAYS --output-type $OUTPUT_TYPE)

          echo "${OUTPUT}"

          if [ -f "$REPORT_FILE" ]; then
            {
              echo "output<<EOF"
              cat "$REPORT_FILE"
              echo "EOF"
            } >> "$GITHUB_OUTPUT"
          else
            echo "Report file not found: $REPORT_FILE"
            exit 1
          fi

      - name: Send email with output as body
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "📊 Daily Coding Group: Leetcode Stats Report"
          to: nyakundi@hotmail.co.uk
          from: LeetCode Accoutability Bot <${{ secrets.EMAIL_USERNAME }}>
          content_type: html
          body: ${{ steps.run-script.outputs.output }}
