name: LeetCode Stats Report

on:
  workflow_dispatch:
    inputs:
      days:
        description: 'Number of days to look back.'
        required: false
        default: '1'
      output_type:
        description: 'Either text or html.'
        required: false
        default: 'html'

  schedule:
    - cron: '0 5 * * *'  # 6 AM London time daily

jobs:
  run-stats:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run CLI and save output
        id: run-script
        run: |
          DAYS="${{ github.event.inputs.days || '1' }}"
          OUTPUT_TYPE="${{ github.event.inputs.output_type || 'text' }}"

          echo "Running stats for over $DAYS days"
          OUTPUT=$(python -m leetcode_accountability.cli stats --days $DAYS --output-type $OUTPUT_TYPE)

          echo "${OUTPUT}"

           # Escape percent signs (optional, for safe GitHub output)
          ESCAPED_OUTPUT="${OUTPUT//'%'/'%25'}"
          ESCAPED_OUTPUT="${ESCAPED_OUTPUT//$'\n'/'%0A'}"
          ESCAPED_OUTPUT="${ESCAPED_OUTPUT//$'\r'/'%0D'}"

          echo "output=$ESCAPED_OUTPUT" >> $GITHUB_OUTPUT

      - name: Send email with output as body
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "📊 Daily Coding Group: Leetcode Stats Report"
          to: nyakundi@hotmail.co.uk
          from: LeetCode Accoutability Bot <${{ secrets.EMAIL_USERNAME }}>
          content_type: html
          body: ${{ steps.run-script.outputs.output }}
