# .github/workflows/run-stats.yml
name: LeetCode Accountability Weekly Run

on:
  # Manual trigger with inputs
  workflow_dispatch:
    inputs:
      email_to:
        description: 'Email address to send the report to.'
        required: false
        default: 'daily-coding-group@googlegroups.com'
  # Scheduled run every Monday at 6 AM London time (5 AM UTC)
  schedule:
    - cron: '30 3 * * 1'

jobs:
  run-stats:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run CLI with correct inputs
        run:
          python -m leetcode_accountability.cli weekly-run --output-type html

      - name: Send email with output as body
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "📊 Daily Coding Group: Weekly Run Report"
          to: ${{ github.event.inputs.email_to || 'daily-coding-group@googlegroups.com' }}
          from: LeetCode Accoutability Bot <${{ secrets.EMAIL_USERNAME }}>
          html_body: file://report.html



